{% set name = "Flask-JSON" %}
{% set pname = "flask-json" %}
{% set version = "0.4.0" %}

package:
  name: {{ pname|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 07945d66024f3b77694ce1db5d1fe83940f2aa3bcad8a608535686be67e4bc48

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - flask >=2.2.0

test:
  imports:
    - flask_json
  requires:
    - pip
  commands:
    - pip check

about:
  license_family: BSD
  license: BSD-3-Clause
  home: https://github.com/skozlovf/flask-json
  license_file: LICENSE
  summary: Better JSON support for Flask
  description: |
    Flask-JSON is a simple extension that adds better JSON support to Flask application
  doc_url: https://flask-json.readthedocs.io
  dev_url: https://github.com/skozlovf/flask-json

extra:
  recipe-maintainers:
    - knaaptime
